changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.{test,spec,stories,storybook}.{js,ts,jsx,tsx}"

nodeLinker: pnp

enableTransparentWorkspaces: true

initScope: "simplecomponent"

initFields:
  description: ""
  version: "0.0.0"
  repository:
    type": git
    url: "https://github.com/phinpho/simplecomponent.git"
    directory: "packages/<!-- name -->"
  type: "module"
  types: "dist/index.d.ts"
  files:
    - "dist"
    - "README.md"
  license: "MIT"
  publishConfig:
    registry: "https://registry.npmjs.org/"
    access: "public"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
