name: Lint and Test

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn workspaces foreach --since=${{ github.ref }} run lint

      - name: Test
        run: yarn workspaces foreach --no-private --since=${{ github.ref }} run test
